version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=12343
      - POSTGRES_DB=project
    ports:
      - 5433:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6378:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8093:8000
    env_file:
      - .env

