# Generated by Django 3.2 on 2021-05-10 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, default='', max_length=252, null=True)),
                ('min_serve_time', models.IntegerField(default=30, verbose_name='Minimum Serve Time')),
                ('min_order_tk', models.FloatField(default=150.0, verbose_name='Minimum Order')),
                ('service_charge', models.FloatField(default=30.0, verbose_name='Service Charge')),
                ('vat_tax', models.FloatField(blank=True, default=0.0, verbose_name='Vat/Tax')),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(max_length=1024)),
                ('environment', models.CharField(max_length=512)),
                ('map_embed_url', models.TextField(default='https://maps.google.com/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_orderable', models.BooleanField(default=False)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_created', to=settings.AUTH_USER_MODEL)),
                ('food_items', models.ManyToManyField(blank=True, to='food.Food')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
