# Generated by Django 3.2 on 2021-05-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.TextField(blank=True)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('ratio', models.CharField(default='1:1', max_length=50)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('ordered_in_restaurant', models.IntegerField(blank=True, default=0)),
                ('ordered_in_home', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodcategory')),
            ],
            options={
                'db_table': 'foods',
            },
        ),
    ]
